# Generated by Django 3.2.9 on 2022-03-22 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_auto_20220322_1001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='drawing',
            new_name='image',
        ),
    ]
