# Generated by Django 3.2.9 on 2022-03-27 10:23

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_rename_drawing_comment_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='content',
            field=markdownx.models.MarkdownxField(blank=True, help_text='Markdown形式で書いてください。', null=True, verbose_name='本文(markdown)'),
        ),
        migrations.CreateModel(
            name='ContentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='画像')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='photos.image')),
            ],
            options={
                'verbose_name': '挿入画像',
                'verbose_name_plural': '挿入画像',
            },
        ),
    ]
