# Generated by Django 3.2.9 on 2022-03-28 10:22

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_auto_20220327_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='content',
            field=mdeditor.fields.MDTextField(blank=True, help_text='Markdown形式で書いてください。', null=True, verbose_name='本文(markdown)'),
        ),
    ]
