# Generated by Django 3.2.9 on 2022-05-06 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0009_image_special'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='date',
            field=models.DateField(null=True, verbose_name='日付'),
        ),
        migrations.AlterField(
            model_name='image',
            name='special',
            field=models.BooleanField(default=False, null=True, verbose_name='特別編'),
        ),
    ]
