# Generated by Django 3.2.9 on 2022-05-18 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0011_auto_20220508_0637'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, verbose_name='名称')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='追加日')),
                ('number', models.PositiveIntegerField(blank=True, null=True, verbose_name='番号')),
            ],
            options={
                'verbose_name': 'タグ',
                'verbose_name_plural': 'タグ',
                'ordering': ['number'],
            },
        ),
        migrations.AddField(
            model_name='image',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='images', to='photos.Tags', verbose_name='タグ'),
        ),
    ]
