# Generated by Django 3.2.9 on 2022-05-19 05:52

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0013_auto_20220519_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='content_rt',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='リッチテキスト形式で書いてください。', null=True, verbose_name='本文(リッチテキスト)'),
        ),
    ]
