# Generated by Django 3.2.9 on 2022-05-24 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0014_image_content_rt'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='cimg_is_public',
            field=models.BooleanField(default=False, null=True, verbose_name='挿入画像を公開する'),
        ),
        migrations.AlterField(
            model_name='contentimage',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='photos.image'),
        ),
    ]
