# Generated by Django 3.2.9 on 2022-05-29 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0016_auto_20220529_2213'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['-date'], 'verbose_name': '投稿', 'verbose_name_plural': '投稿'},
        ),
    ]
