# Generated by Django 3.2.9 on 2022-06-03 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0017_alter_image_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_url', models.URLField(null=True, verbose_name='サイトURL')),
                ('title', models.CharField(blank=True, max_length=500, null=True, verbose_name='タイトル')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='画像URL')),
                ('description', models.TextField(blank=True, null=True, verbose_name='詳細')),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metadata', to='photos.image', verbose_name='アルバム')),
            ],
        ),
    ]
