# Generated by Django 3.2.9 on 2022-06-03 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0019_auto_20220603_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadata',
            name='site_name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='サイト名'),
        ),
    ]
