# Generated by Django 3.2.9 on 2022-06-04 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0020_metadata_site_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='cimg_is_public',
            field=models.BooleanField(default=True, null=True, verbose_name='ギャラリーの公開'),
        ),
    ]
