# Generated by Django 3.2.9 on 2022-06-04 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0022_metadata_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='photos.image', verbose_name='アルバム'),
        ),
    ]
