# Generated by Django 3.2.9 on 2022-06-04 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0023_alter_metadata_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentimage',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='登録日時'),
        ),
        migrations.AddField(
            model_name='contentimage',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='メモ'),
        ),
        migrations.AddField(
            model_name='contentimage',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新日時'),
        ),
    ]
