# Generated by Django 3.2.9 on 2022-06-06 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0024_auto_20220605_0454'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadata',
            name='family',
            field=models.BooleanField(default=False, null=True, verbose_name='手作り'),
        ),
    ]
