# Generated by Django 3.2.9 on 2022-06-07 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0025_metadata_family'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created'], 'verbose_name': 'コメント', 'verbose_name_plural': 'コメント'},
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200, null=True, verbose_name='投稿者')),
                ('text', models.TextField(null=True, verbose_name='本文')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='作成日時')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='更新日時')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='photos.comment', verbose_name='コメント')),
            ],
            options={
                'verbose_name': '返信',
                'verbose_name_plural': '返信',
                'ordering': ['created'],
            },
        ),
    ]
