# Generated by Django 3.2.9 on 2022-06-08 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0026_auto_20220607_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='draft',
            field=models.BooleanField(default=False, null=True, verbose_name='下書き'),
        ),
    ]
