# Generated by Django 3.2.9 on 2022-06-08 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0027_image_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentimage',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_images', to='photos.comment', verbose_name='コメント'),
        ),
    ]
