# Generated by Django 3.2.9 on 2022-06-10 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0029_contentimage_reply'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplyLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=300, null=True, verbose_name='ユーザー')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='作成日時')),
                ('reply', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='photos.reply', verbose_name='返信')),
            ],
            options={
                'verbose_name': 'いいね(返信)',
                'verbose_name_plural': 'いいね(返信)',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=300, null=True, verbose_name='ユーザー')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='作成日時')),
                ('comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='photos.comment', verbose_name='コメント')),
            ],
            options={
                'verbose_name': 'いいね(コメント)',
                'verbose_name_plural': 'いいね(コメント)',
                'ordering': ['-created'],
            },
        ),
    ]
