# Generated by Django 3.2.9 on 2022-06-12 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0031_auto_20220611_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='author',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='投稿者'),
        ),
    ]
