# Generated by Django 3.2.9 on 2022-06-12 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0032_image_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['-date'], 'verbose_name': 'アルバム', 'verbose_name_plural': 'アルバム'},
        ),
    ]
