# Generated by Django 3.2.9 on 2022-06-12 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0033_alter_image_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentimage',
            name='author',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='投稿者'),
        ),
        migrations.AddField(
            model_name='metadata',
            name='author',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='投稿者'),
        ),
    ]
