# Generated by Django 3.2.9 on 2022-06-13 20:03

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0034_auto_20220613_0514'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='投稿者ID')),
                ('author_name', models.CharField(blank=True, max_length=300, null=True, verbose_name='投稿者名')),
                ('title', models.CharField(max_length=300, null=True, verbose_name='名前')),
                ('thumbnail', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='サムネイル')),
                ('video', cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='動画')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='追加日')),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='photos.image', verbose_name='アルバム')),
            ],
            options={
                'verbose_name': '動画',
                'verbose_name_plural': '動画',
                'ordering': ['-created'],
            },
        ),
    ]
