# Generated by Django 3.2.9 on 2022-06-14 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0035_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='名前'),
        ),
    ]
