# Generated by Django 3.2.9 on 2022-06-14 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0036_alter_video_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='thumbnail',
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='タイトル'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.URLField(null=True, verbose_name='動画URL'),
        ),
    ]
