# Generated by Django 3.2.9 on 2022-06-14 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0037_auto_20220614_1204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='video',
            new_name='url',
        ),
    ]
