# Generated by Django 3.2.9 on 2022-06-15 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0038_rename_video_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='public_id',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='パブリックID'),
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.URLField(blank=True, null=True, verbose_name='サムネイル'),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='タイトル'),
        ),
    ]
