# Generated by Django 3.2.9 on 2022-06-16 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0039_auto_20220616_0524'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='bytes',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='バイト'),
        ),
    ]
