# Generated by Django 3.2.9 on 2022-06-16 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0040_video_bytes'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='photos.comment', verbose_name='コメント'),
        ),
        migrations.AddField(
            model_name='video',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='photos.reply', verbose_name='返信'),
        ),
    ]
