# Generated by Django 3.2.9 on 2021-11-16 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, null=True, verbose_name='タイトル')),
                ('field', models.CharField(blank=True, max_length=300, null=True, verbose_name='畑')),
                ('task', models.CharField(blank=True, max_length=300, null=True, verbose_name='内容')),
                ('description', models.TextField(blank=True, null=True, verbose_name='詳細')),
                ('start', models.DateTimeField(blank=True, null=True, verbose_name='開始時間')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='終了時間')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='作成日時')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='更新日時')),
                ('is_public', models.BooleanField(blank=True, default=False, null=True, verbose_name='完成')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='完成日時')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
