# Generated by Django 3.2.9 on 2021-11-16 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created'], 'verbose_name': '日報', 'verbose_name_plural': '日報'},
        ),
        migrations.RenameField(
            model_name='article',
            old_name='end',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='start',
            new_name='start_time',
        ),
        migrations.AddField(
            model_name='article',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='画像①'),
        ),
        migrations.AddField(
            model_name='article',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='画像②'),
        ),
    ]
