# Generated by Django 3.2.9 on 2021-11-18 03:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('farm', '0003_auto_20211117_0542'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='field',
            options={'ordering': ['name'], 'verbose_name': '畑', 'verbose_name_plural': '畑'},
        ),
        migrations.AlterModelOptions(
            name='pears',
            options={'ordering': ['name'], 'verbose_name': '品種', 'verbose_name_plural': '品種'},
        ),
        migrations.AddField(
            model_name='article',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー'),
        ),
        migrations.AlterField(
            model_name='article',
            name='field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='farm.field', verbose_name='畑'),
        ),
        migrations.AlterField(
            model_name='article',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='articles', to='farm.Images', verbose_name='画像'),
        ),
        migrations.AlterField(
            model_name='article',
            name='pears',
            field=models.ManyToManyField(blank=True, related_name='articles', to='farm.Pears', verbose_name='品種'),
        ),
    ]
