# Generated by Django 3.2.9 on 2021-11-22 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0005_auto_20211118_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='field',
        ),
        migrations.AddField(
            model_name='article',
            name='field',
            field=models.ManyToManyField(blank=True, related_name='articles', to='farm.Field', verbose_name='作業場'),
        ),
    ]
