# Generated by Django 3.2.9 on 2021-11-22 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0006_auto_20211122_1445'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Field',
            new_name='Fields',
        ),
        migrations.RemoveField(
            model_name='article',
            name='field',
        ),
        migrations.AddField(
            model_name='article',
            name='fields',
            field=models.ManyToManyField(blank=True, related_name='articles', to='farm.Fields', verbose_name='作業場'),
        ),
    ]
