# Generated by Django 3.2.9 on 2021-11-22 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0007_auto_20211122_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='task',
        ),
        migrations.AddField(
            model_name='article',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='日付'),
        ),
    ]
