# Generated by Django 3.2.9 on 2021-11-22 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0008_auto_20211122_2030'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'アルバム',
                'verbose_name_plural': 'アルバム',
            },
        ),
        migrations.AddField(
            model_name='images',
            name='default',
            field=models.BooleanField(default=False, null=True, verbose_name='初期設定'),
        ),
        migrations.AddField(
            model_name='images',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='名前'),
        ),
        migrations.AddField(
            model_name='article',
            name='album',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article', to='farm.imagealbum'),
        ),
        migrations.AddField(
            model_name='images',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='farm.imagealbum'),
        ),
    ]
