# Generated by Django 3.2.9 on 2021-11-22 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0010_auto_20211123_0537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='name',
        ),
        migrations.AddField(
            model_name='images',
            name='url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='URL'),
        ),
    ]
