# Generated by Django 3.2.9 on 2021-11-24 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0012_auto_20211124_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='コメント'),
        ),
    ]
