# Generated by Django 3.2.9 on 2021-11-25 01:58

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0014_linepush'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='linepush',
            options={'ordering': ['-create_time'], 'verbose_name': 'LINE登録', 'verbose_name_plural': 'LINE登録'},
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='画像ファイル'),
        ),
    ]
