# Generated by Django 3.2.9 on 2021-11-25 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0015_auto_20211125_1058'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fields',
            options={'ordering': ['number'], 'verbose_name': '作業場', 'verbose_name_plural': '作業場'},
        ),
        migrations.AlterModelOptions(
            name='pears',
            options={'ordering': ['number'], 'verbose_name': '品種', 'verbose_name_plural': '品種'},
        ),
        migrations.AddField(
            model_name='fields',
            name='number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='番号'),
        ),
        migrations.AddField(
            model_name='pears',
            name='number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='番号'),
        ),
        migrations.AlterField(
            model_name='article',
            name='fields',
            field=models.ManyToManyField(blank=True, related_name='articles', to='farm.Fields', verbose_name='作業場所'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=300, null=True, verbose_name='作業内容'),
        ),
    ]
