# Generated by Django 3.2.9 on 2021-11-27 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0016_auto_20211125_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, null=True, verbose_name='名前')),
                ('number', models.PositiveIntegerField(blank=True, null=True, verbose_name='番号')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='追加日')),
            ],
            options={
                'verbose_name': '分類',
                'verbose_name_plural': '分類',
                'ordering': ['number'],
            },
        ),
        migrations.AlterModelOptions(
            name='fields',
            options={'ordering': ['number'], 'verbose_name': '作業場所', 'verbose_name_plural': '作業場所'},
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='farm.category', verbose_name='分類'),
        ),
    ]
