# Generated by Django 3.2.9 on 2021-11-28 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0018_auto_20211127_1803'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
