# Generated by Django 3.2.9 on 2021-12-03 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0020_comment_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='author',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='投稿者'),
        ),
    ]
