# Generated by Django 3.2.9 on 2021-12-10 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0024_auto_20211211_0815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentlike',
            name='users',
        ),
        migrations.AddField(
            model_name='commentlike',
            name='user',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='ユーザー'),
        ),
    ]
