# Generated by Django 3.2.9 on 2021-12-17 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0025_auto_20211211_0825'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=300, null=True, verbose_name='ユーザー')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='作成日時')),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='farm.article', verbose_name='いいね')),
            ],
            options={
                'verbose_name': 'いいね(日報)',
                'verbose_name_plural': 'いいね(日報)',
                'ordering': ['-created'],
            },
        ),
    ]
