# Generated by Django 3.2.9 on 2021-12-29 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0026_articlelike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlelike',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='farm.article', verbose_name='日報'),
        ),
        migrations.AlterField(
            model_name='commentlike',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='farm.comment', verbose_name='コメント'),
        ),
    ]
