# Generated by Django 3.2.9 on 2021-12-29 02:08

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawing',
            name='url_one',
            field=models.URLField(blank=True, null=True, verbose_name='URL①'),
        ),
        migrations.AddField(
            model_name='drawing',
            name='url_two',
            field=models.URLField(blank=True, null=True, verbose_name='URL②'),
        ),
        migrations.AlterField(
            model_name='drawing',
            name='image_one',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='画像①'),
        ),
        migrations.AlterField(
            model_name='drawing',
            name='image_two',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='画像②'),
        ),
    ]
