# Generated by Django 3.2.9 on 2021-12-29 02:26

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawings', '0002_auto_20211229_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawing',
            name='comment',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='コメント'),
        ),
        migrations.AlterField(
            model_name='drawing',
            name='image_one',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='画像①'),
        ),
    ]
