# Generated by Django 3.2.9 on 2021-12-31 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawings', '0003_auto_20211229_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawing',
            name='date',
            field=models.DateField(null=True, verbose_name='作成日'),
        ),
    ]
