# Generated by Django 3.2.9 on 2022-01-29 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drawings', '0005_auto_20220130_0646'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='pic',
            new_name='drawing',
        ),
    ]
