# Generated by Django 3.2.9 on 2022-03-22 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drawings', '0006_rename_pic_comment_drawing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drawing',
            name='url_one',
        ),
        migrations.RemoveField(
            model_name='drawing',
            name='url_two',
        ),
    ]
