# Generated by Django 3.2.9 on 2022-05-06 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawings', '0008_alter_drawing_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawing',
            name='creator',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='作者'),
        ),
    ]
