# Generated by Django 3.2.9 on 2022-05-07 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawings', '0010_alter_drawing_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawing',
            name='creator',
            field=models.CharField(choices=[('1', '仁菜'), ('2', '拓海'), ('3', '沙織'), ('4', '祥太朗')], default='1', max_length=300, null=True, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='drawing',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='メモ'),
        ),
    ]
